display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: تلاش
          exposed_sorts_label: 'کی طرف سے  کی گئی مرتب سازی'
      pager:
        options:
          tags:
            previous: '› گزشتہ'
            next: اگلا>
      filters:
        search_api_fulltext:
          expose:
            label: تلاش
