display:
  default:
    display_title: मुळस्वरुप
    display_options:
      exposed_form:
        options:
          reset_button_label: पुर्ववत
          exposed_sorts_label: 'क्रमवारी नुसार लावा'
      empty:
        title:
          title: '[site:name] मध्ये आपले स्वागत'
  page_1:
    display_title: पान
