display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: पुर्ववत
          exposed_sorts_label: 'क्रमवारी नुसार लावा'
      fields:
        name:
          separator: ', '
        pid:
          separator: ', '
        css_style:
          separator: ', '
        operations:
          label: कृती
      filters:
        name:
          expose:
            label: नाव
  page_1:
    display_title: पान
