display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: पुर्ववत
          exposed_sorts_label: 'क्रमवारी नुसार लावा'
      pager:
        options:
          tags:
            previous: '‹ मागे'
            next: 'पुढे ›'
            first: '« प्रथम'
            last: 'अंतिम »'
      fields:
        title:
          label: शीर्षक
          separator: ', '
        type:
          label: प्रकार
          separator: ', '
        name:
          label: लेखक
          separator: ', '
        changed:
          label: सुधारित
          separator: ', '
        imported:
          separator: ', '
        operations:
          label: कृती
      filters:
        title:
          expose:
            label: शीर्षक
        type:
          expose:
            label: प्रकार
  page_1:
    display_title: पान
