intercom.settings:
  type: config_object
  mapping:
    intercom_mode:
      type: integer
      label: 'Mode'
    intercom_test_app_id:
      type: string
      label: 'Intercom test App ID'
    intercom_live_app_id:
      type: string
      label: 'Intercom production App ID'
    intercom_an_only:
      type: boolean
      label: 'Anonymous users only'
