display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: 'लागू करें'
          reset_button_label: 'दोबारा से स्थापित करें|'
          exposed_sorts_label: 'क्रमबद्ध द्वारा'
          sort_desc_label: अवरोही
      pager:
        options:
          tags:
            previous: '‹ पिछले'
            next: 'अगला >'
            first: '« प्रथम'
            last: 'अन्तिम »'
          expose:
            items_per_page_label: 'विषय प्रति पृष्ठ'
            items_per_page_options_all_label: '-सभी-'
      fields:
        title:
          label: शीर्षक
          separator: ', '
        type:
          label: प्रकार
          separator: ', '
        name:
          label: लेखक
          separator: ', '
        changed:
          label: अद्यतित
          separator: ', '
        imported:
          separator: ', '
        operations:
          label: कार्यवाही
      filters:
        title:
          expose:
            label: शीर्षक
        type:
          expose:
            label: प्रकार
  page_1:
    display_title: पृष्ठ
