_core:
  default_config_hash: t2LzrClibyhtJD_yHiWZ6AyD-EYKhe94rOo3dUGLLUU
admin_css: true
fx: ''
noscript: false
responsive_image: false
one_pixel: true
placeholder: ''
unstyled_extensions: ''
extras: {  }
blazy:
  loadInvisible: false
  offset: 100
  saveViewportOffsetDelay: 50
  validateDelay: 25
  container: ''
io:
  unblazy: false
  rootMargin: 0px
  threshold: '0'
  disconnect: false
