_core:
  default_config_hash: TghDxAeHu4gER0JZhzPbMawpRgxggVsIu54oyTeaJOo
load_all_enabled_fonts: 1
enabled_fonts:
  - 'https://www.google.com/webfonts/family?family=Oswald&subset=cyrillic-ext#500'
  - 'https://www.google.com/webfonts/family?family=Montserrat&subset=cyrillic#500'
  - 'https://www.google.com/webfonts/family?family=Montserrat&subset=cyrillic-ext#500'
  - 'https://www.google.com/webfonts/family?family=Montserrat&subset=latin-ext#500'
  - 'https://www.google.com/webfonts/family?family=Montserrat&subset=latin#500'
  - 'https://www.google.com/webfonts/family?family=Montserrat&subset=vietnamese#500'
  - 'https://www.google.com/webfonts/family?family=Montserrat&subset=cyrillic-ext#500italic'
  - 'https://www.google.com/webfonts/family?family=Montserrat&subset=cyrillic#500italic'
  - 'https://www.google.com/webfonts/family?family=Montserrat&subset=latin-ext#500italic'
  - 'https://www.google.com/webfonts/family?family=Montserrat&subset=latin#500italic'
  - 'https://www.google.com/webfonts/family?family=Montserrat&subset=vietnamese#500italic'
  - 'https://www.google.com/webfonts/family?family=Montserrat&subset=cyrillic-ext#600'
  - 'https://www.google.com/webfonts/family?family=Montserrat&subset=cyrillic#600'
  - 'https://www.google.com/webfonts/family?family=Montserrat&subset=cyrillic-ext#100'
  - 'https://www.google.com/webfonts/family?family=Montserrat&subset=cyrillic#100'
  - 'https://www.google.com/webfonts/family?family=Montserrat&subset=latin-ext#100'
  - 'https://www.google.com/webfonts/family?family=Montserrat&subset=latin#100'
  - 'https://www.google.com/webfonts/family?family=Montserrat&subset=vietnamese#100'
  - 'https://www.google.com/webfonts/family?family=Montserrat&subset=cyrillic-ext#100italic'
  - 'https://www.google.com/webfonts/family?family=Oswald&subset=cyrillic-ext#300'
  - 'https://www.google.com/webfonts/family?family=Oswald&subset=cyrillic#300'
  - 'https://www.google.com/webfonts/family?family=Oswald&subset=latin-ext#300'
  - 'https://www.google.com/webfonts/family?family=Oswald&subset=latin#300'
  - 'https://www.google.com/webfonts/family?family=Oswald&subset=vietnamese#300'
  - 'https://www.google.com/webfonts/family?family=Roboto&subset=cyrillic-ext#100'
  - 'https://www.google.com/webfonts/family?family=Roboto&subset=cyrillic#100'
  - 'https://www.google.com/webfonts/family?family=Roboto&subset=greek-ext#100'
  - 'https://www.google.com/webfonts/family?family=Roboto&subset=greek#100'
  - 'https://www.google.com/webfonts/family?family=Roboto&subset=latin-ext#100'
  - 'https://www.google.com/webfonts/family?family=Roboto&subset=latin#100'
  - 'https://www.google.com/webfonts/family?family=Roboto&subset=vietnamese#100italic'
  - 'https://www.google.com/webfonts/family?family=Roboto&subset=cyrillic-ext#100italic'
  - 'https://www.google.com/webfonts/family?family=Roboto&subset=vietnamese#100'
  - 'https://www.google.com/webfonts/family?family=Roboto&subset=latin#100italic'
  - 'https://www.google.com/webfonts/family?family=Roboto&subset=cyrillic#100italic'
  - 'https://www.google.com/webfonts/family?family=Roboto&subset=greek-ext#100italic'
  - 'https://www.google.com/webfonts/family?family=Roboto&subset=greek#100italic'
  - 'https://www.google.com/webfonts/family?family=Roboto&subset=latin-ext#100italic'
  - 'https://www.google.com/webfonts/family?family=Roboto&subset=vietnamese#300italic'
  - 'https://www.google.com/webfonts/family?family=Roboto&subset=cyrillic-ext#300'
  - 'https://www.google.com/webfonts/family?family=Roboto&subset=cyrillic#300'
  - 'https://www.google.com/webfonts/family?family=Roboto&subset=cyrillic-ext#500'
  - 'https://www.google.com/webfonts/family?family=Roboto&subset=cyrillic#500'
  - 'https://www.google.com/webfonts/family?family=Roboto&subset=cyrillic-ext#500italic'
  - 'https://www.google.com/webfonts/family?family=Roboto&subset=cyrillic#500italic'
  - 'https://www.google.com/webfonts/family?family=Roboto&subset=cyrillic-ext#700'
  - 'https://www.google.com/webfonts/family?family=Roboto&subset=cyrillic#700'
  - 'https://www.google.com/webfonts/family?family=Roboto&subset=cyrillic-ext#700italic'
  - 'https://www.google.com/webfonts/family?family=Roboto&subset=vietnamese#700'
  - 'https://www.google.com/webfonts/family?family=PT Sans&subset=cyrillic-ext#700'
  - 'https://www.google.com/webfonts/family?family=PT Sans&subset=cyrillic#700'
  - 'https://www.google.com/webfonts/family?family=PT Sans&subset=latin-ext#700'
  - 'https://www.google.com/webfonts/family?family=PT Sans&subset=latin#700'
  - 'https://www.google.com/webfonts/family?family=PT Sans&subset=cyrillic-ext#700italic'
  - 'https://www.google.com/webfonts/family?family=PT Sans&subset=cyrillic#700italic'
  - 'https://www.google.com/webfonts/family?family=PT Sans Caption&subset=cyrillic-ext#700'
  - 'https://www.google.com/webfonts/family?family=PT Sans Caption&subset=cyrillic#700'
  - 'https://www.google.com/webfonts/family?family=PT Sans Caption&subset=latin-ext#700'
  - 'https://www.google.com/webfonts/family?family=PT Sans Caption&subset=latin#700'
  - 'https://www.google.com/webfonts/family?family=PT Sans Caption&subset=cyrillic-ext#regular'
  - 'https://www.google.com/webfonts/family?family=PT Sans&subset=latin-ext#regular'
  - 'https://www.google.com/webfonts/family?family=PT Sans&subset=latin#regular'
  - 'https://www.google.com/webfonts/family?family=PT Sans Narrow&subset=cyrillic-ext#regular'
  - 'https://www.google.com/webfonts/family?family=PT Sans Narrow&subset=cyrillic#regular'
  - 'https://www.google.com/webfonts/family?family=PT Sans Narrow&subset=latin-ext#regular'
  - 'https://www.google.com/webfonts/family?family=PT Sans Narrow&subset=latin#regular'
  - 'https://www.google.com/webfonts/family?family=PT Sans&subset=cyrillic-ext#regular'
  - 'https://www.google.com/webfonts/family?family=PT Sans&subset=cyrillic#regular'
  - 'https://www.google.com/webfonts/family?family=PT Sans Narrow&subset=cyrillic#700'
  - 'https://www.google.com/webfonts/family?family=PT Sans Narrow&subset=cyrillic-ext#700'
  - 'https://www.google.com/webfonts/family?family=PT Sans Narrow&subset=latin-ext#700'
  - 'https://www.google.com/webfonts/family?family=PT Sans Narrow&subset=latin#700'
  - 'https://www.google.com/webfonts/family?family=PT Sans&subset=latin#700italic'
  - 'https://www.google.com/webfonts/family?family=PT Sans&subset=latin-ext#700italic'
  - 'https://www.google.com/webfonts/family?family=PT Sans Caption&subset=cyrillic#regular'
  - 'https://www.google.com/webfonts/family?family=PT Sans Caption&subset=latin-ext#regular'
  - 'https://www.google.com/webfonts/family?family=PT Sans Caption&subset=latin#regular'
  - 'https://www.google.com/webfonts/family?family=PT Sans&subset=cyrillic-ext#italic'
  - 'https://www.google.com/webfonts/family?family=PT Sans&subset=cyrillic#italic'
  - 'https://www.google.com/webfonts/family?family=PT Sans&subset=latin#italic'
  - 'https://www.google.com/webfonts/family?family=PT Sans&subset=latin-ext#italic'
  - 'https://www.google.com/webfonts/family?family=PT Serif&subset=cyrillic-ext#regular'
  - 'https://www.google.com/webfonts/family?family=PT Serif&subset=cyrillic#regular'
  - 'https://www.google.com/webfonts/family?family=PT Serif&subset=latin-ext#regular'
  - 'https://www.google.com/webfonts/family?family=PT Serif&subset=latin#regular'
  - 'https://www.google.com/webfonts/family?family=PT Serif&subset=latin#italic'
  - 'https://www.google.com/webfonts/family?family=PT Serif&subset=latin-ext#italic'
  - 'https://www.google.com/webfonts/family?family=PT Serif Caption&subset=cyrillic-ext#regular'
  - 'https://www.google.com/webfonts/family?family=PT Serif Caption&subset=cyrillic#regular'
  - 'https://www.google.com/webfonts/family?family=PT Serif Caption&subset=latin-ext#regular'
  - 'https://www.google.com/webfonts/family?family=PT Serif Caption&subset=latin#regular'
  - 'https://www.google.com/webfonts/family?family=PT Serif&subset=cyrillic-ext#italic'
  - 'https://www.google.com/webfonts/family?family=PT Serif&subset=cyrillic#italic'
  - 'https://www.google.com/webfonts/family?family=PT Serif Caption&subset=latin#italic'
  - 'https://www.google.com/webfonts/family?family=PT Serif Caption&subset=latin-ext#italic'
  - 'https://www.google.com/webfonts/family?family=PT Serif Caption&subset=cyrillic#italic'
  - 'https://www.google.com/webfonts/family?family=PT Serif Caption&subset=cyrillic-ext#italic'
  - 'https://www.google.com/webfonts/family?family=PT Serif&subset=latin#700italic'
  - 'https://www.google.com/webfonts/family?family=PT Serif&subset=latin-ext#700italic'
  - 'https://www.google.com/webfonts/family?family=PT Serif&subset=cyrillic-ext#700'
  - 'https://www.google.com/webfonts/family?family=PT Serif&subset=cyrillic#700'
  - 'https://www.google.com/webfonts/family?family=PT Serif&subset=latin-ext#700'
  - 'https://www.google.com/webfonts/family?family=PT Serif&subset=latin#700'
  - 'https://www.google.com/webfonts/family?family=PT Serif&subset=cyrillic-ext#700italic'
  - 'https://www.google.com/webfonts/family?family=PT Serif&subset=cyrillic#700italic'
load_on_themes: {  }
