features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://the-wire-logo.png'
favicon:
  use_default: 0
  path: 'public://thewire-favicon_0.png'
  mimetype: image/png
